version: "3.8"

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    networks:
      - app_network
    volumes:
      - ./backend:/app
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      - tesseract

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    networks:
      - app_network
    volumes:
      - ./frontend:/app
    stdin_open: true
    tty: true
    depends_on:
      - backend

  tesseract:
    image: tesseractshadow/tesseract4re
    restart: unless-stopped
    networks:
      - app_network

networks:
  app_network: